### ISSUE TITLE
Crashing upon multiplayer games starting up, mods or not.

### ISSUE THREAD

**Issue by heyhey546** [Robosturm/Commander_Wars#77]
The title is pretty self-explanatory, but you asked for extra details on Discord.
Gamerules: Default.
Map: Sun Canal.
Connected via: Internet, host portforwarding.
Who crashes: Myself, but the host would also crash upon ending turn.
As for if we tried changing who goes first, how do you do that? We never noticed any option to change that.

**Comment by Robosturm** [comment]
If the client crashes did you get the countdown from 5 to 1 before the crash?
If yes i may found a possible bug for that one at least.
If the host played his turn did you(client) see the units appear he produced?

As for changing who goes first:
-  the Host can make the second player human as well.
- And afterwards make the first player Open
- Last you join the game and you're the first player.
- Than try to make your turn and end it and tell me if it crashes.

Thx for the information i hope i can track down the bugs with that information.
I may send you a hotfix version attached to this issue when i added some possible fixes. 
So you can tell me if they worked. :)

**Comment by heyhey546** [comment]
The countdown does get from 5 to 1, but as soon as it hits 1, the game crashes. So no, I did not see what units get produced. Pretty sure my animation speed is unchanged from the default. I'll ask about the 4th question but I'm pretty sure they can. Thank you for the information on how to change turn order, too, I'll also try checking that out.

**Comment by Robosturm** [comment]
So i think i fixed the client crash issue.
Still searching for the Host crash on the next turn action...
Did you get the info if they can see the units beeing produced on the client?

**Comment by heyhey546** [comment]
Ok, so, we've tried making it so I join as the first player. Now a new issue has risen, that being, I no longer crash, I get sent back to the menu where you join rooms from, and rather than the host crashing upon starting the turn, they just straight up crashed when the countdown ended.

**Comment by heyhey546** [comment]
Should mention, this problem persisted with two friends, so it's not exclusive to one.

**Comment by Robosturm** [comment]
I found some possible reasons for the crash, but i'm not sure if i fixed it for the next release.
I added crash reporting to the next release took me the most time of this release.
So if the game crashes i get a small log where and why the game crashed, which should in theory help me to fix the bug easily if i didn't fix it yet.
Sry that this one takes a little longer, but it seems to be a weird timing dependend bug which is hard to reproduce on my machine but easy on yours. :(

**Comment by heyhey546** [comment]
Alright, looking forward to that release, then.

**Comment by heyhey546** [comment]
Okay, seems the issue hasn't been resolved. The countdown ended, and the game stopped responding. The host's game also froze. However the CO music could still be heard while it had stopped responding.

**Comment by Robosturm** [comment]
Sounds like the crashreporter freezed.... Weird since it has an max cycle timer... Normally a crash report should show up. After some seconds up to 1 or 2 mins.

Could you check if a file exists in the folder logs and if it post it here. Thx.

**Comment by heyhey546** [comment]
[20200107-143924 Commander Wars Crash.log](https://github.com/Robosturm/Commander_Wars/files/4055815/20200107-143924.Commander.Wars.Crash.log)
Here it is.

**Comment by Robosturm** [comment]
Okay found the bug which is related to the crashlog you send me.
However it seems that a CO-Sprite is missing as well. Could you tell me with which CO you tried to play the game?
Since the error is that the game couldn't find the CO-Sprite.

**Comment by heyhey546** [comment]
I used Robosturm and the host used Rachel.

**Comment by heyhey546** [comment]
Any idea which it is? Should we just use different characters and see if it works?

**Comment by Robosturm** [comment]
Does playing a singleplayer game with Robosturm and Rachel crashes the game?
If so the bug is a defected installation of Commander Wars either by a active mod or by damaged files.

As for the actual bug i found another issue which can lead to a crash which i fixed for the next release. Though i'm only 95% sure that it's the bug you initially had.

**Comment by heyhey546** [comment]
Sorry I took so long, but I finally took a look into it. Singleplayer does NOT crash with Robosturm and/or Rachel. Only multiplayer.

**Comment by Robosturm** [comment]
Hmm. Well i fxied several bugs concerning multiplayer. Since than.
Could you check if it still crashes with the prerelease here:
https://github.com/Robosturm/Commander_Wars/releases/tag/Beta_13_pre
And if it crashes send me the crashreport. Thx.

**Comment by Robosturm** [comment]
Multiple people are using portforwaring wright now and it works so i close the issue for now
